import XCTest
import AppKit
@testable import Core
@testable import OpenClip

final class PasteboardCopyEngineTests: XCTestCase {
    private static let pasteboardName = NSPasteboard.Name("com.openclip.tests.copyengine")

    @MainActor
    private func makePasteboard() -> NSPasteboard {
        let pasteboard = NSPasteboard(name: Self.pasteboardName)
        pasteboard.clearContents()
        return pasteboard
    }

    @MainActor
    func testTriggerChangesContentReturnsNewStringRestoresOriginalWithTransientMarkers() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Copied", forType: .string)
        }

        XCTAssertEqual(captured?.text, "Copied")

        // The original is restored synchronously before capture returns — no delayed cleanup
        // task that could race and leave the copied text behind.
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")

        let transient = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")) ?? Data()
        let autoGenerated = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")) ?? Data()
        XCTAssertEqual(transient, Data())
        XCTAssertEqual(autoGenerated, Data())
    }

    @MainActor
    func testTriggerWritingBackSameTextReturnsText() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Original", forType: .string)
        }

        // The changeCount advances, so the write is accepted even though the value matches the
        // archived original (a re-copy of the same text is a legitimate copy).
        XCTAssertEqual(captured?.text, "Original")
    }

    @MainActor
    func testTimeoutWithUntouchedPasteboardDoesNotRestoreOrAlterChangeCount() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)
        let initialChangeCount = pasteboard.changeCount

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // Trigger never copies: the changeCount never advances.
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
        XCTAssertEqual(pasteboard.changeCount, initialChangeCount, "Untouched pasteboard must not be cleared, restored, or advanced")
        XCTAssertNil(pasteboard.data(forType: PasteboardSnapshot.transientType), "Untouched pasteboard must not have transient markers added")
        XCTAssertNil(pasteboard.data(forType: PasteboardSnapshot.autoGeneratedType), "Untouched pasteboard must not have auto-generated markers added")
    }

    @MainActor
    func testTimeoutWithModifiedPasteboardRestoresOriginalWithTransientMarkers() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // Trigger copies whitespace: advances changeCount, but yields no substantial text
            pasteboard.clearContents()
            pasteboard.setString("   ", forType: .string)
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
        XCTAssertNotNil(pasteboard.data(forType: PasteboardSnapshot.transientType))
        XCTAssertNotNil(pasteboard.data(forType: PasteboardSnapshot.autoGeneratedType))
    }

    @MainActor
    func testSnapshotCapturePreservesLazyAndPromisedTypes() throws {
        let pasteboard = makePasteboard()
        class LazyProvider: NSObject, NSPasteboardItemDataProvider {
            func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {}
        }
        let provider = LazyProvider()
        let item = NSPasteboardItem()
        let lazyType = NSPasteboard.PasteboardType("com.openclip.test.lazy")
        item.setDataProvider(provider, forTypes: [lazyType])
        pasteboard.writeObjects([item])

        let snapshot = PasteboardSnapshot.capture(pasteboard)
        XCTAssertEqual(snapshot.items.count, 1, "Snapshot must not drop items that only contain promised/lazy types")
        XCTAssertTrue(snapshot.items.first?.types.contains(lazyType) == true, "Snapshot item must preserve promised type")
    }

    @MainActor
    func testSnapshotCapturePreservesPropertyListWhenDataIsNil() throws {
        let pasteboard = makePasteboard()
        let filenamesType = NSPasteboard.PasteboardType("NSFilenamesPboardType")
        pasteboard.declareTypes([filenamesType], owner: nil)
        pasteboard.setPropertyList(["/Users/test/file.txt"], forType: filenamesType)

        let snapshot = PasteboardSnapshot.capture(pasteboard)
        XCTAssertFalse(snapshot.items.isEmpty, "Snapshot must not drop file list items")
        
        let restoredPB = makePasteboard()
        snapshot.restore(to: restoredPB, transientMarkers: false)
        let restoredFiles = restoredPB.propertyList(forType: filenamesType) as? [String]
        XCTAssertEqual(restoredFiles, ["/Users/test/file.txt"])
    }

    @MainActor
    func testTimeoutWithLazyPasteboardItemDoesNotWipeClipboard() async throws {
        let pasteboard = makePasteboard()
        class LazyProvider: NSObject, NSPasteboardItemDataProvider {
            func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {}
        }
        let provider = LazyProvider()
        let item = NSPasteboardItem()
        let lazyType = NSPasteboard.PasteboardType("com.openclip.test.lazy")
        item.setDataProvider(provider, forTypes: [lazyType])
        pasteboard.writeObjects([item])
        let initialChangeCount = pasteboard.changeCount

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // Trigger does not copy
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.changeCount, initialChangeCount, "Untouched lazy pasteboard must not have changeCount advanced")
        XCTAssertEqual(pasteboard.pasteboardItems?.count, 1, "Untouched lazy pasteboard must not lose items")
        XCTAssertTrue(pasteboard.pasteboardItems?.first?.types.contains(lazyType) == true, "Untouched lazy pasteboard must retain lazy type")
    }

    @MainActor
    func testTransientEmptyWriteThenTextIsCaptured() async {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 1.0,
            restoreDelay: 0.05
        ) {
            // Simulate the PopClip-style race: the changeCount advances with empty content first,
            // then the real selection lands a beat later.
            Task { @MainActor in
                pasteboard.clearContents()
                pasteboard.setString("", forType: .string)
                try? await Task.sleep(nanoseconds: 20_000_000)
                pasteboard.clearContents()
                pasteboard.setString("Real selection", forType: .string)
            }
        }

        XCTAssertEqual(captured?.text, "Real selection")
    }

    @MainActor
    func testCaptureReadsHtmlAndRtfRepresentations() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Rich selection", forType: .string)
            pasteboard.setString("<b>Rich selection</b>", forType: .html)
            pasteboard.setString("{\\rtf1 Rich selection}", forType: .rtf)
        }

        XCTAssertEqual(captured?.text, "Rich selection")
        XCTAssertEqual(captured?.html, "<b>Rich selection</b>")
        XCTAssertEqual(captured?.rtf, "{\\rtf1 Rich selection}")
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
    }

    @MainActor
    func testCaptureConvertsRTFToHTMLWhenNoHTMLRepresentation() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let attributed = NSAttributedString(string: "Rich selection")
        let rtfData = try attributed.data(
            from: NSRange(location: 0, length: attributed.length),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]
        )

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Rich selection", forType: .string)
            pasteboard.setData(rtfData, forType: .rtf)
        }

        XCTAssertEqual(captured?.text, "Rich selection")
        XCTAssertNotNil(captured?.html)
        XCTAssertTrue(captured?.html?.contains("Rich selection") == true)
    }

    @MainActor
    func testHasSelection() {
        XCTAssertFalse(PasteboardCopyEngine.hasSelection(nil))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("   "))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{00A0}\u{00A0}")) // Non-breaking spaces
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{200B}\u{FEFF}")) // Zero-width spaces
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{0000}")) // Null byte
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("x"))
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("  hello  "))
    }

    @MainActor
    func testBrowserPollingTimeout() {
        XCTAssertEqual(
            PasteboardCopyEngine.pollingTimeout(for: "com.google.Chrome"),
            Constants.safariPasteboardCopyTimeout
        )
        XCTAssertEqual(
            PasteboardCopyEngine.pollingTimeout(for: "org.mozilla.firefox"),
            Constants.safariPasteboardCopyTimeout
        )
        XCTAssertEqual(
            PasteboardCopyEngine.pollingTimeout(for: "com.apple.Safari"),
            Constants.safariPasteboardCopyTimeout
        )
        XCTAssertEqual(
            PasteboardCopyEngine.pollingTimeout(for: "company.thebrowser.Browser"),
            Constants.safariPasteboardCopyTimeout
        )
        XCTAssertEqual(
            PasteboardCopyEngine.pollingTimeout(for: "com.apple.TextEdit"),
            Constants.pasteboardCopyTimeout
        )
    }
}