// PasteboardSnapshot.swift
// OpenClip
//
// Standalone utility for capturing and restoring NSPasteboard contents across platform
// side-effects and selection-retrieval mechanisms, tagging restored items with transient markers
// so third-party clipboard managers do not record the restore as a user-visible copy.
import AppKit

/// Immutable snapshot of pasteboard items that can be restored with transient markers.
@MainActor
public struct PasteboardSnapshot: @unchecked Sendable {
    public static let transientType = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")

    public let items: [NSPasteboardItem]

    public init(items: [NSPasteboardItem]) {
        self.items = items
    }

    /// Captures every type's data off every pasteboard item so the content can be restored verbatim.
    public static func capture(_ pasteboard: NSPasteboard = .general) -> PasteboardSnapshot {
        guard let items = pasteboard.pasteboardItems else {
            return PasteboardSnapshot(items: [])
        }
        let copies: [NSPasteboardItem] = items.compactMap { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    copy.setData(data, forType: type)
                } else if let string = item.string(forType: type) {
                    copy.setString(string, forType: type)
                } else if let plist = item.propertyList(forType: type) {
                    copy.setPropertyList(plist, forType: type)
                } else {
                    // Fallback for lazy/promised types providing nil synchronously: register empty Data
                    // so the item retains its declared type in the snapshot rather than being dropped entirely (fix #34).
                    copy.setData(Data(), forType: type)
                }
            }
            return copy.types.isEmpty ? nil : copy
        }
        return PasteboardSnapshot(items: copies)
    }

    /// Writes the archived items back to the pasteboard.
    ///
    /// - Parameters:
    ///   - pasteboard: The pasteboard to restore to (defaults to .general).
    ///   - transientMarkers: When true (default), tags each item with the nspasteboard transient /
    ///     auto-generated markers (empty data) so clipboard managers skip the restore as a user-visible copy.
    public func restore(to pasteboard: NSPasteboard = .general, transientMarkers: Bool = true) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        if transientMarkers {
            for item in items {
                item.setData(Data(), forType: Self.transientType)
                item.setData(Data(), forType: Self.autoGeneratedType)
            }
        }
        pasteboard.writeObjects(items)
    }
}
